@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center

mainframe 5.3.19 Virologist forgets their genetic codes by AmnesiaVirus

participant "v: Virologist" as v
participant "av: AmnesiaVirus" as av
participant "i: Inventory" as i

-> v ++: myTurn()
    v -> av ++ : onTurnImpact(v)
        av -> v ++:getInventory()
        return i
        loop for all gCode: GeneticCode
            av -> i ++ :removeGeneticCode(gCode)
            return
        end
    return
    note across : The player will choose their actions here in the real game

    v -> av ++ : endTurnImpact(v)
    return
    v -> av ++ : decrement(v)
    return
return
@enduml