@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center

mainframe XXX Virologist forgets their genetic codes by Amnesiavirus

participant "v: Virologist" as v
participant "av: AmnesiaVirus" as av
participant "i: Inventory" as i

-> v ++: myTurn()
    v -> av ++ : onTurnImpact(v)
        av -> v ++:getInventory()
        return i
        loop for all gCode: GeneticCode
            av -> i ++ :removeGeneticCode(gCode)
            return
        end
    return
    ...
    v -> av ++ : endTurnImpact(v)
    return

return
@enduml