@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center

mainframe 5.3.20 Virologist can pick up more resources with enlarged Bag.

participant "v: Virologist" as v
participant "b: Bag" as b
participant "i: Inventory" as i
participant "w: Warehouse" as w
participant "newRes: Resource" as newRes

-> v ++ : myTurn()
    v -> b ++ : onTurnImpact(v)
        b -> v ++ : getInventory()
        return i
        b -> i ++ : getMaxResourceAmount()
        return x
        b -> i ++ : setMaxResourceAmount(2*x)
        return
    return

    note across : The player will choose their actions here in the real game

    v -> b ++ : endTurnImpact(v)
            b -> v ++ : getInventory()
            return i
            b -> i ++ : getMaxResourceAmount()
            return x
            b -> i ++ : setMaxResourceAmount(x/2)
            return
        return
return
@enduml