@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam sequenceMessageAlign center

mainframe  Virologist crafts an AmnesiaVirus

participant "v: Virologist" as v
participant "i: Inventory" as i
participant "g: GeneticCode" as g
participant "a: AmnesiaVirus" as a1
participant "price: Resource"
participant "newAmnesia: AmnesiaVirus" as a2


 -> v ++ : craft(g)
        v -> g ++ : craft(i)
            loop for all price: Resource
                g -> i ++ : removeResource(price)
                return
            end
            note over g, a1 : Clones the AmnesiaVirus stored in the agent attribute
            g -> a1 ++ : create()
                a1 -> a2 ** : <<create>>
            return newAmnesia
            g -> i ++ : addCraftedAgent(newAmnesia)
            return
        return
return

@enduml