@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center

mainframe 5.3.1 Virologist moves to EmptyTile

participant "v: Virologist" as v
participant "activeTile: EmptyTile" as t1
participant "e: EmptyTile" as e

-> v ++: moveTo(e)
    v -> t1 ++ : removeVirologist(v)
    return
    v -> e ++ : addVirologist(v)
    return
return
@enduml