@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center

mainframe Virologist moves to Laboratory

actor Player as p
participant "v: Virologist" as v
participant "activeTile: EmptyTile" as t1
participant "l: Laboratory" as l

p -> v++ : move()
    v -> t1 ++ : getNeighbours()
    return neighbours
return neighbours

p -> v ++: moveTo(l)
    v -> t1 ++ : removeVirologist(v)
    return
    v -> l ++ : addVirologist(v)
    return
return
@enduml