@startuml
hide footbox
skinparam sequenceMessageAlign center

mainframe S-Z-Á-M useVitusDanceVirus
participant "vdv: VitusDanceVirus" as vdv
participant "v2: Virologist" as v2
participant "e: Effect" as e
participant "v1: Virologist" as v1

 -> vdv++ : use(v1,v2)
    vdv -> v2++ : getActiveEffects()
    return activeEffects
    vdv -> v2++ : addEffect(vdv)
    return
    opt v1 != v2
        loop for all e in activeEffects
            vdv -> e++ : counterImpact(vdv, v1, v2)
            return
        end
    end
 return
@enduml
