@startuml
hide footbox
skinparam sequenceMessageAlign center

mainframe S-Z-Á-M useVaccine
participant "v: Vaccine" as v
participant "v2: Virologist" as v2
participant "e: Effect" as e
participant "v1: Virologist" as v1

 -> v++ : use(v1,v2)
    v -> v2++ : getActiveEffects()
    return activeEffects
    v -> v2++ : addEffect(v)
    return
    opt v1 != v2
        loop for all e in activeEffects
            v -> e++ : counterImpact(v, v1, v2)
            return
        end
    end
 return
@enduml