@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam sequenceMessageAlign center

mainframe 3.4.5 Virologist forget their genetic codes by Amnesiavirus

participant "v: Virologist" as v
participant "av: AmnesiaVirus" as av
participant "i: Inventory" as i

note over v, av : This function gets called in myTurn
v -> av ++ : onTurnImpact(v)
    av -> v ++:getInventory()
    return i
    loop for all gCode: GeneticCode
        av -> i ++ :removeGeneticCode(gCode)
        return
    end
return
@enduml