@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam sequenceMessageAlign center

mainframe 3.4.6 Bag enlarges Virologist's inventory.

participant "v: Virologist" as v
participant "b: Bag" as b
participant "i: Inventory" as i

note over v, b : This function gets called in myTurn
v -> b ++ : onTurnImpact(p)
    b -> v ++ : getInventory()
    return i
    b -> i ++ : getMaxResourceAmount()
    return x
    b -> i ++ : setMaxResourceAmount(2*x)
    return
return
@enduml