@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center

mainframe 3.4.7 Virologist is stunned

participant "v: Virologist" as v
participant "sv: StunVirus" as sv

note over v, sv : This function gets called in myTurn
v -> sv ++: onTurnImpact(v)
    sv -> v ++: getActionsLeft()
    return actionsLeft
    loop while actionsLeft > 0
        sv -> v ++: pass()
        return
        sv -> v ++: getActionsLeft()
        return actionsLeft
    end
return
@enduml