@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center

mainframe 4.4.9 Virologist moves to another Tile

actor Player as p
participant "v: Virologist" as v
participant "activeTile: Tile" as t1
participant "t2: Tile" as t2
participant "vX: Virologist" as vX
participant "e: Effect" as e

p -> v++ : move()
    v -> t1 ++ : getNeighbours()
    return neighbours
return neighbours
note over p,v: Player chooses 't2' from neighbours
p -> v ++: moveTo(t2)
    v -> t1 ++ : removeVirologist(v)
    return
    v -> t2 ++ : addVirologist(v)
        loop for all vX : t2.players
            t2 -> vX ++ : getActiveEffects()
            return activeEffects
            loop for all e : activeEffects
                t2 -> e ++ : infect(vX)
                return
            end
        end
    return
return
@enduml