@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam sequenceMessageAlign center

mainframe 4.4.10 Virologist picks up equipment

actor Player as p
participant "v: Virologist" as v
participant "s: Safehouse" as s
participant "newEq: Equipment" as newEq
participant "i: Inventory" as i

p -> v ++ : pickUp()
    v -> s ++ : collectItem(i)
        s -> newEq ** : <<create>>
        s -> newEq ++ : collect(i)
            newEq -> i ++ : addEquipment(newEq)
                i -> v ++ : addEffect(newEq)
                return
            return
        return
    return
return

@enduml