@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam sequenceMessageAlign center

mainframe 3.4.11 Virologist learns a new genetic code

actor Player as p
participant "v: Virologist" as v
participant "l: Laboratory" as l
participant "newGc: GeneticCode" as newGc
participant "i: Inventory" as i

p -> v ++ : pickUp()
    v -> l ++ : collectItem(i)
        l -> g ++ : collect(i)
            g -> i ++ : addGeneticCode(g)
            return
        return
    return
return

@enduml