@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam sequenceMessageAlign center

mainframe 4.4.15 Glove's CounterImpact throws agent back

participant "a: Agent" as a
participant "g: Glove" as g
participant "v1: Virologist" as v1
participant "v2: Virologist" as v2
participant "v1Inv: Inventory" as v1Inv

note over a, g : This function gets called in virologistUsesAgent
a-> g ++: counterImpact(a, v1, v2)
    opt v1 != null
        g -> v2 ++: removeEffect(a)
        return
        g -> v1 ++: addEffect(a)
        return
        g -> g ++: durabilityDecreases(v) /'Should have an unbreaking enchantment'/
        opt usesLeft == 0
            g -> v1 ++: removeEffect(g)
            return
            g -> v1 ++ : getInventory()
            return v1Inv
            g -> v1Inv ++ : removeEquipment(g)
            return
        end
        return
    end
return

@enduml