@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center
mainframe The Protective Cloak's counterImpact saves the Virologist from getting affected

participant "a: Agent" as a
participant "c: ProtectiveCloak" as c
participant "v2: Virologist" as v2
participant "v1: Virologist" as v1

note over a,c: This function gets called in virologistUsesAgent
a -> c ++: counterImpact(a, v1, v2)
    note over c :getting a random number\n from 1 to 1000
    opt randomNumber <= 823
        c -> v2 ++: removeEffect(a)
        return
    end
return
@enduml