@startuml
'https://plantuml.com/sequence-diagram

hide footbox
mainframe Virologist forget their genetic codes by Amnesiavirus
skinparam sequenceMessageAlign center

actor Player as p1

participant "v: Virologist" as v
participant "av: AmnesiaVirus" as av
participant "i: Inventory" as i

v -> av ++ : onTurnImpact(v)
    av -> v ++:getInventory()
    return i
    loop for all gCode: GeneticCode
        av -> i ++ :removeGeneticCode(gCode)
        return
    end
return
@enduml