@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam sequenceMessageAlign center

mainframe Bag on turn impact

participant "v: Virologist" as v
participant "b: Bag" as b
participant "i: Inventory" as i

    v -> b ++ : onTurnImpact(p)
        b -> v ++ : getInventory()
        return i
        b -> i ++ : getMaxResourceAmount()
        return x
        b -> i ++ : setMaxResourceAmount(2*x)
        return
    return

@enduml