@startuml
'https://plantuml.com/sequence-diagram

participant "v1: Virologist" as v1
participant "a: Agent" as a
participant "g: Glove" as g
participant "v2: Virologist" as v2
Participant "g: Glove" as g

v1 -> a ++: use(v1,v2)
    a -> v2 ++: addEffect(a)
    return
    a-> g ++: counterImpact(a, v1, v2)
        g -> v2++: removeEffect(a)
        return
        g -> v1++: addEffect(a))
        return
    return
return




@enduml