@startuml
'https://plantuml.com/sequence-diagram


hide footbox
skinparam sequenceMessageAlign center
mainframe Virologist stunned with Stunvirus by another Virologist

actor Player as p1

participant "v1: Virologist" as v1
participant "v2: Virologist" as v2
participant "sv: StunVirus" as sv

p1 -> v1 ++: useAgent(sv, v2)
v1 -> v2 ++: addEffect(sv)
return
return
@enduml