@startuml
'https://plantuml.com/sequence-diagram
hide footbox
skinparam sequenceMessageAlign center
mainframe The Vaccine's CounterImpact saves Virologist from getting affected

participant "a: Agent" as a
participant "vac: Vaccine" as vac
participant "v2: Virologist" as v2
participant "v1: Virologist" as v1

a -> vac ++: counterImpact(a, v1, v2)
    vac -> v2++: removeEffect(a)
    return
return

@enduml