@startuml
'https://plantuml.com/sequence-diagram

hide footbox
skinparam sequenceMessageAlign center
mainframe Virologist add vitus dance virus to another virologist

participant "v: Virologist" as v
participant "dv: VitusDanceVirus" as dv
participant "t: Tile" as t

v -> dv ++: onTurnImpact(v)
    dv -> v ++: getActionsLeft()
    return actionsLeft
    loop for actionsLeft > 0
        dv -> v ++: getActiveTile()
        return t: Tile
        dv -> t ++: getNeighbours()
        return neighbours: Tile[]
        note over dv: A number is generated between 0\n and the number of neighbours - 1
        dv -> v ++: moveTo(neighbours[randomNumber])
        return
        dv -> v ++: getActionsLeft()
        return actionsLeft
    end
return
@enduml