@startuml
left to right direction
(Step) as (lep)
(Learn genetic code) as (gen)
(Craft an agent) as (cr_ag)
(Use an agent) as (use_ag)
(Pick up resources) as (pu_mat)
(Pick up an equipment) as (pu_eq)
(Steal from another player) as (steal)
(Time passing by) as (time)

actor Player as j1
actor Controller as k
k --> time
j1 --> lep
j1 --> gen
j1 --> cr_ag
j1 --> use_ag
j1 --> pu_mat
j1 --> pu_eq
j1 --> steal
@enduml