@startuml
'https://plantuml.com/state-diagram
left to right direction
mainframe Agent states
hide empty description

state Created
state Destroyed
state Activated
[*] --> Created
Created --> Created : roundLeft > 0
Created --> Destroyed : roundLeft <= 0
Created --> Activated : use(from, to)
Activated --> Activated : roundLeft > 0
Activated --> Destroyed : roundLeft <= 0
Destroyed-->[*]
@enduml