@startuml
'https://plantuml.com/state-diagram

left to right direction
mainframe Agent states
hide empty description

state Created
state Activated
[*] --> Created
Created --> [*] : decrement [roundsLeft == 0]
Created --> Activated : use
Activated --> Activated : decrement [roundsLeft >= 0]
Activated -->[*] : decrement [roundsLeft == 0]
@enduml

