@startuml
left to right direction
actor Player as P
'actor Controller as C

'Question on all: On yourself or on others?
'Does the tile have other players?
'Question in counterImpact: Does the virologist, who has been thrown at, have cloak, glove or vaccine
(useAmnesiaVirus) as uAv
(useStunVirus) as uSv
(useVitusDanceVirus) as uVdv
(useVaccine) as uV

(forgetCodesViaAmnesiaVirus) as fca
(enlargeTheBag) as etb
(stunnedPlayerMissesTurn) as spm
(playerVitusDances) as pvd

/' Crafts viruses (I don't think we need all of them separately)'/
(craftVaccine) as cV
(craftVitusDance) as cVd
(craftAmnesia) as cA
(craftStun) as cS

/' Moves to tile types '/
(pickUpBag) as pB
(pickUpCloak) as pC
(pickUpGlove) as pG
(pickUpResource) as pRES
(learnGeneticCode)  as lGC

(moveToWarehouse) as mWh
(moveToSafehouse) as mSh
(moveToLaboratory) as mL
(moveToEmptyTile) as mEt



/' Scenes '/
(robVirologist) as rv

P -left-> mWh
P -left-> mSh
P -left-> mL
P -left-> mEt

P -up-> uAv
P -up-> uSv
P -up-> uVdv
P -up-> uV

P -up-> fca
P -up-> etb
P -down-> spm
P -down-> pvd

P -right-> cA
P -right-> cS
P -right-> cVd
P -right-> cV

P -down-> rv
P -down-> pG
P -down-> pC
P -down-> pB
P -down-> lGC
P -down-> pRES

/' Controller test-cases '/

'(createMap) as cM
'(nextRound) as nR
'
'C --> cM
'C --> nR

@enduml