@startuml
left to right direction
actor Player as P
actor Controller as C

/' Vírusokat felken '/
(useAgentOnNakedVirologist) as uAONV
(useAgentOnVirologistWithGlove) as uAOVWG
(useAgentOnVirologistWithCloak) as uAOVWC
(useAgentOnVirologistWithVaccine) as uAOVWV

/' Vírusokat craftol (szerintem nem kell mindegyiket külön)'/
(craftAgentWithEnoughResoruces) as cA /'x4'/
(craftAgentWithoutEnoughResources) as cA2 /'x4'/
'Konkrét adatokkal

/' Mező típusokra lép '/
(pickUpEquipmentEnoughSpace) as pEQ
(pickUpEquipmentNotEnoughSpace) as pEQN
(pickUpResourceEnoughSpace) as pRES
(pickUpResourceNotEnoughSpace) as pRESN
(learnGeneticCode)  as lGC
(learnGeneticCodeVictory) as lGCV

/' Scenes '/
(stunnedPlayerBeingRobbed) as sPBR
(tryingToRobNotStunnedPlayer) as tTRNSP
(useStunOnStunned) as uSOS
(useAgentThat'sAlreadyActive) as uATAA

P -up-> uAONV
P -up-> uAOVWG
P -up-> uAOVWC
P -up-> uAOVWV
P -left-> pEQ
P -left-> pEQN
P -left-> pRES
P -left-> pRESN
P -left-> lGC
P -left-> lGCV
P -right-> cA
P -right-> cA2
P -down-> sPBR
P -down-> tTRNSP
P -down-> uSOS
P -down-> uATAA

/' Controller test-cases '/

(createMap) as cM
(nextRound) as nR

C --> cM
C --> nR



@enduml